---
env:
  es6: true
  node: true
plugins:
  - "sort-class-members"
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
rules:
  "@typescript-eslint/indent":
    - 2
    - 4
    - SwitchCase: 1
      ignoreComments: false
  "@typescript-eslint/no-empty-function": 0
  "@typescript-eslint/no-explicit-any": 0
  "@typescript-eslint/consistent-type-definitions": 2
  "@typescript-eslint/semi":
    - 2
    - always
  "@typescript-eslint/ban-ts-comment":
    - 2
    - ts-expect-error: allow-with-description
      ts-ignore: allow-with-description
  eol-last: 2
  keyword-spacing:
    - 2
    - after: true
  lines-between-class-members:
    - 2
    - always
  no-async-promise-executor: 0
  no-prototype-builtins: 0
  no-trailing-spaces: 2
  no-var: 2
  object-curly-spacing:
    - 2
    - always
  padding-line-between-statements:
    - 2
    - blankLine: always
      prev: [multiline-block-like, directive]
      next: "*"
    - blankLine: always
      prev: "*"
      next: multiline-block-like
  quotes:
    - 2
    - double
  semi:
    - 2
    - always
  sort-class-members/sort-class-members:
    - 2
    - order:
        - "[screaming-snake-case-static-properties]"
        - "[alphabetical-properties]"
        - constructor
        - "[alphabetical-getters]"
        - "[alphabetical-methods]"
        - "on"
        - "[everything-else]"
      groups:
        screaming-snake-case-static-properties:
          - name: "/^[A-Z_0-9]+$/"
            type: property
        alphabetical-properties:
          - type: property
            sort: alphabetical
        alphabetical-getters:
          - kind: get
            sort: alphabetical
        alphabetical-methods:
          - type: method
            sort: alphabetical